name: Rust Build CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile complete --default-toolchain stable

      - name: Setup env
        run: . "$HOME/.cargo/env"
      - name: Setup System
        run: sudo apt update && sudo apt install gcc clang qemu-utils qemu-system-x86 qemu-system-gui cmake make -y

      - name: Build with Cargo
        run: rustup override set nightly && rustup target add x86_64-unknown-none && rustup component add rust-src && rustup component add llvm-tools && cargo build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: .
          retention-days: 90
          if-no-files-found: error
          compression-level: 0
